### PR TITLE
Fix getCodeLenses logic

### LINKED ISSUE #902: [Bug] getCodeLenses method ignores codelenses in span after first
`getCodeLenses` ignores codelenses in span after first

**Describe the bug** 
In case you have codelenses in span:
Screenshot from 2023-08-09 10-49-08

html:

```
<span class="codelens-decoration" widgetid="codelens.widget-1" monaco-visible-content-widget="true" style="position: absolute; display: block; visibility: inherit; max-width: 200px; top: -3px; left: 0px;">

    <a id="0" title="Run integration file with Camel JBang and attach the Camel Debugger.
    Take care that the integration file is in supported scope of Camel JBang and that jbang CLI is available on system path." role="button">Camel Debug with JBang</a>
   
    </a><span>&nbsp;|&nbsp;</span>

    <a id="1" title="Run integration file with Camel JBang.
    Take care that the integration file is in supported scope of Camel JBang and that jbang CLI is available on system path." role="button">Camel Run with JBang    

</span>
```
Logs:

```
Search with getCodeLens 'Camel Run with JBang': undefined
Search with getCodeLens 'Camel Debug with JBang': [object Object]
Count codelenses with getCodeLenses: 1
```
Logs (In case of the order change):
```
Search with getCodeLens 'Camel Run with JBang': [object Object]
Search with getCodeLens 'Camel Debug with JBang': undefined
Count codelenses with getCodeLenses: 1
```

**Steps to Reproduce**
1. Use `getCodeLenses` method on horizontal codelenses sequence 
2. Check array length 
3. or/and try to return the second codelens object with `getCodeLens`

**Expected behavior**
- `getCodeLenses` method returns all CodeLenses

### PR DESCRIPTION
**Pull request by unsortedhashsets**
Hi, 

Changed logic:

1. getCodeLenses, xpath changed from `.//span[contains(@widgetid, 'codelens.widget')]` to `.//span[contains(@widgetid, 'codelens.widget')]/a[@id]` to select all codelenses and not codelenses container
2. CodeLens constructor changed from `super(element.findElement(By.css('a')), editor);` to `super(element, editor);`

So these changes should fix #902 reported bug 

Check for new xpath ->
xpath-check

---

Before submitting your PR, please review the following checklist:

- [X] adding a new test if your PR resolves an issue.
- [X] **DO** keep pull requests small so they can be easily reviewed.
- [X] **DO** make sure tests pass.
~- **DO** make sure any public APIs changes are documented.~ No changes 
- [X] **DO** make sure not to introduce any compiler warnings.

Before merging the PR:
- [ ] **CHECK** continous integration of main branch is green.
- [ ] **CHECK** pull request check job is green.
- [ ] **CHECK** all pull request questions/requests are resolved.
- [ ] **WAIT** till PR is approved by at least 1 committer.

### CODE REVIEW

**Review by djelinek — APPROVED** [review]

File: page-objects/src/components/editor/TextEditor.ts [hunk 1]
```diff
@@ -549,7 +548,7 @@ class Selection extends ElementWithContexMenu {
  */
 export class CodeLens extends AbstractElement {
     constructor(element: WebElement, editor: TextEditor) {
```
Comment (djelinek) [inline page-objects/src/components/editor/TextEditor.ts:550]: by this change, the constructor becomes useless and can be removed

**Review by djelinek — CHANGES_REQUESTED** [review]

**Comment by djelinek** [comment]
@unsortedhashsets it would be nice to also modify codelens provider (https://github.com/redhat-developer/vscode-extension-tester/blob/main/test/test-project/src/codelensProvider.ts) and tests to check also more codelens are now possible to work with

**Comment by unsortedhashsets** [comment]
> @unsortedhashsets it would be nice to also modify codelens provider (https://github.com/redhat-developer/vscode-extension-tester/blob/main/test/test-project/src/codelensProvider.ts) and tests to check also more codelens are now possible to work with

will try, thanks!
